blank_issues_enabled: false
contact_links:
  - name: New feature? Tell us about it on GitHub Discussions
    url: https://github.com/pathwaycom/pathway/discussions
    about: We are using Discussions as a place to connect with other members of the Pathway community.
  - name: Discord
    url: https://discord.com/invite/pathway
    about: Ask questions you are wondering about.
