#!/usr/bin/env python
# coding: utf-8

# <a href="https://colab.research.google.com/github/pathwaycom/pathway-examples/blob/main/documentation/from_jupyter_to_deploy/part3_kafka_data_streamer.ipynb" target="_parent"><img src="https://pathway.com/assets/colab-badge.svg" alt="Run In Colab" class="inline"/></a>

# # Installing Pathway with Python 3.10+
#
# In the cell below, we install Pathway into a Python 3.10+ Linux runtime.
#
# > **If you are running in Google Colab, please run the colab notebook (Ctrl+F9)**, disregarding the 'not authored by Google' warning.
# >
# > **The installation and loading time is less than 1 minute**.
#

# In[ ]:


# get_ipython().run_cell_magic('capture', '--no-display', '!pip install pathway\n')


# This is a helper notebook to stream data from CSV to Kafka.

# In[1]:


# OPTIONAL Download CSV file
# get_ipython().system('wget -nc https://gist.githubusercontent.com/janchorowski/e351af72ecd8d206a34763a428826ab7/raw/ticker.csv')


# In[2]:


import datetime

import pathway as pw

fname = "ticker.csv"
schema = pw.schema_from_csv(fname)


# In[3]:


print(schema.generate_class(class_name="DataSchema"))


# In[4]:


# The schema definition is autogenerated
class DataSchema(pw.Schema):
    ticker: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float
    t: int
    transactions: int
    otc: str


data = pw.demo.replay_csv(fname, schema=DataSchema, input_rate=1000)


# In[5]:


# TODO: please set appropriaye values for KAFKA_ENDPOINT, KAFKA_USERNAME, and KAFKA_PASSWORD
rdkafka_producer_settings = {
    "bootstrap.servers": "kafka:9092",
    "security.protocol": "plaintext",
}

pw.io.kafka.write(data, rdkafka_producer_settings, topic_name="ticker")


# In[6]:


pw.run()
